version: '3.1'

services:
  nginx_my_server:
    build: ../Part5
    restart: always
    tty: true

  nginx_default:
    image: nginx
    restart: always
    ports:
      - 80:8080
    depends_on:
      - nginx_my_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf